### ISSUE TITLE
more icebreaker issues (crash on startup)

### ISSUE THREAD

**Issue by mattdm** [libsdl-org/sdl12-compat#304] opened 2023-07-13 20:53 UTC
Over 20 years ago, I wrote a game called Icebreaker. People still like it! Someone already addressed one issue with it here (amazing!) — #68 

However, with Fedora Linux 35 it started having hard-to-reproduce crash-on-startup issues. As of F38, it seems to crash on startup _all the time_, so... progress?

I will freely admit this is not good code. I should re-write it all -- it still might not be good code, but at least I'll be using Bevy Engine and Rust rather than _making everything up_ and _not knowing how to do memory management in C so it's just a bunch of arrays_. :)

But, until that time, which may never come.... it's not working, and figuring it out alone is beyond me.

I get...

```
Thread 3 "icebrea:disk$0" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe7fff6c0 (LWP 334025)]
0x0000000000418800 in flock ()
(gdb) bt
#0  0x0000000000418800 in flock ()
#1  0x00007ffff48bbbfc in disk_cache_write_item_to_disk
    (dc_job=dc_job@entry=0x7fffd403e6b0, filename=filename@entry=0x7fffe0000b70 "/home/mattdm/.cache/mesa_shader_cache/0a/3f0df508dae8286fb2ffd4379e8b34176ddb05")
    at ../src/util/disk_cache_os.c:765
#2  0x00007ffff48ba185 in cache_put (job=job@entry=0x7fffd403e6b0, gdata=gdata@entry=0x0, thread_index=thread_index@entry=0) at ../src/util/disk_cache.c:460
#3  0x00007ffff48c3e41 in util_queue_thread_func (input=input@entry=0x5c7350) at ../src/util/u_queue.c:309
#4  0x00007ffff4912ecc in impl_thrd_routine (p=<optimized out>) at ../src/c11/impl/threads_posix.c:67
#5  0x00007ffff7dd3907 in start_thread (arg=<optimized out>) at pthread_create.c:444
#6  0x00007ffff7e59870 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
(gdb) 
```

User reports at https://discussion.fedoraproject.org/t/icebreaker-on-fedora-35-and-sadly-up/35254/7 and https://bugzilla.redhat.com/show_bug.cgi?id=2048689

If someone could help, that would be _amazing_.

**Comment by smcv** [comment] 2023-07-18 00:47
For what it's worth, it seemed OK when run with sdl12-compat on Debian 12, when I tried to test all the remaining SDL 1.2 games in Debian.

**Comment by mattdm** [comment] 2023-07-18 04:11
FWIW, whatever is happening is happening _very early_, in the call to `SDL_SetVideoMode()`. 

I would like to emphasize again the possibility that I did something very stupid in the code, or in the hand-crafted makefile.

**Comment by Conan-Kudo** [comment] 2024-12-03 21:53
I'm still observing this problem, though it seems it slightly improved with sdl2-compat in that it draws the window and a black box before crashing.

```
(gdb) bt
#0  0x000055555556c560 in flock ()
#1  0x00007fffd9021132 in mesa_db_flock (file=<optimized out>, op=<optimized out>) at ../src/util/mesa_cache_db.c:105
#2  mesa_db_lock (db=0x55555577f890) at ../src/util/mesa_cache_db.c:120
#3  0x00007fffd9021555 in mesa_db_load (db=db@entry=0x55555577f890, reload=reload@entry=false) at ../src/util/mesa_cache_db.c:346
#4  0x00007fffd9021ed3 in mesa_cache_db_open (db=db@entry=0x55555577f890, cache_path=<optimized out>) at ../src/util/mesa_cache_db.c:685
#5  0x00007fffd900e3da in mesa_cache_db_multipart_init_part_locked (db=0x5555556e5f70, part=0) at ../src/util/mesa_cache_db_multipart.c:60
#6  mesa_cache_db_multipart_init_part (db=db@entry=0x5555556e5f70, part=part@entry=0) at ../src/util/mesa_cache_db_multipart.c:93
#7  0x00007fffd900e667 in mesa_cache_db_multipart_init_part (db=0x5555556e5f70, part=0) at ../src/util/mesa_cache_db_multipart.c:89
#8  mesa_cache_db_multipart_read_entry (db=db@entry=0x5555556e5f70, cache_key_160bit=cache_key_160bit@entry=0x7fffffffba00 "\220\232\315O\300\217\354mv\304\303q\371\377\340\374\346\226j\263\377\177", size=size@entry=0x7fffffffb910) at ../src/util/mesa_cache_db_multipart.c:136
#9  0x00007fffd9000c7c in disk_cache_db_load_item (cache=cache@entry=0x5555556e5de0, key=key@entry=0x7fffffffba00 "\220\232\315O\300\217\354mv\304\303q\371\377\340\374\346\226j\263\377\177", size=size@entry=0x7fffffffb9c8) at ../src/util/disk_cache_os.c:1167
#10 0x00007fffd8fff2be in disk_cache_get (cache=cache@entry=0x5555556e5de0, key=key@entry=0x7fffffffba00 "\220\232\315O\300\217\354mv\304\303q\371\377\340\374\346\226j\263\377\177", size=size@entry=0x7fffffffb9c8) at ../src/util/disk_cache.c:605
#11 0x00007fffd8f78553 in vk_pipeline_cache_lookup_object (cache=0x5555556e0110, key_data=key_data@entry=0x55555587f0a0, key_size=key_size@entry=20, ops=ops@entry=0x7fffd996a510 <radv_pipeline_ops>, cache_hit=<optimized out>) at ../src/vulkan/runtime/vk_pipeline_cache.c:365
#12 0x00007fffd8ed3bc6 in radv_pipeline_cache_object_search (device=device@entry=0x555555730fe0, cache=<optimized out>, cache@entry=0x0, pipeline=pipeline@entry=0x55555587f060, found_in_application_cache=found_in_application_cache@entry=0x7fffffffbb27) at ../src/amd/vulkan/radv_pipeline_cache.c:298
#13 0x00007fffd8ed4085 in radv_graphics_pipeline_cache_search (device=device@entry=0x555555730fe0, cache=cache@entry=0x0, pipeline=pipeline@entry=0x55555587f060, found_in_application_cache=found_in_application_cache@entry=0x7fffffffbb27) at ../src/amd/vulkan/radv_pipeline_cache.c:314
#14 0x00007fffd8eda5f7 in radv_graphics_pipeline_compile (pipeline=pipeline@entry=0x55555587f060, pCreateInfo=pCreateInfo@entry=0x7fffffffc6d0, gfx_state=gfx_state@entry=0x7fffffffbd50, device=device@entry=0x555555730fe0, cache=cache@entry=0x0, fast_linking_enabled=fast_linking_enabled@entry=false)
    at ../src/amd/vulkan/radv_pipeline_graphics.c:2730
#15 0x00007fffd8edbbe8 in radv_graphics_pipeline_init (pipeline=pipeline@entry=0x55555587f060, device=device@entry=0x555555730fe0, cache=cache@entry=0x0, pCreateInfo=pCreateInfo@entry=0x7fffffffc6d0, extra=extra@entry=0x0) at ../src/amd/vulkan/radv_pipeline_graphics.c:3134
#16 0x00007fffd8edc95e in radv_graphics_pipeline_create (_device=_device@entry=0x555555730fe0, _cache=_cache@entry=0x0, pCreateInfo=pCreateInfo@entry=0x7fffffffc6d0, extra=extra@entry=0x0, pAllocator=pAllocator@entry=0x0, pPipeline=pPipeline@entry=0x5555559ba280) at ../src/amd/vulkan/radv_pipeline_graphics.c:3204
#17 0x00007fffd8edccf9 in radv_CreateGraphicsPipelines (_device=<optimized out>, pipelineCache=<optimized out>, count=<optimized out>, pCreateInfos=<optimized out>, pAllocator=<optimized out>, pPipelines=<optimized out>) at ../src/amd/vulkan/radv_pipeline_graphics.c:3347
#18 0x00007ffff79a22fd in VULKAN_CreateGraphicsPipeline (driverData=<optimized out>, createinfo=<optimized out>) at /usr/src/debug/SDL3-3.1.6-1.fc41.x86_64/src/gpu/vulkan/SDL_gpu_vulkan.c:6454
#19 0x00007ffff78728e5 in MakePipeline (device=0x5555556d5e20, shaders=0x555555642438, params=<synthetic pointer>) at /usr/src/debug/SDL3-3.1.6-1.fc41.x86_64/src/render/gpu/SDL_pipeline_gpu.c:180
#20 GPU_GetPipeline (cache=0x555555642468, shaders=0x555555642438, device=0x5555556d5e20, params=<synthetic pointer>) at /usr/src/debug/SDL3-3.1.6-1.fc41.x86_64/src/render/gpu/SDL_pipeline_gpu.c:210
#21 Draw (data=data@entry=0x555555642430, cmd=0x55555577f310, num_verts=6, offset=0, prim=SDL_GPU_PRIMITIVETYPE_TRIANGLELIST) at /usr/src/debug/SDL3-3.1.6-1.fc41.x86_64/src/render/gpu/SDL_render_gpu.c:567
#22 0x00007ffff7872deb in GPU_RunCommandQueue (renderer=0x555555642150, cmd=<optimized out>, vertices=<optimized out>, vertsize=<optimized out>) at /usr/src/debug/SDL3-3.1.6-1.fc41.x86_64/src/render/gpu/SDL_render_gpu.c:814
#23 0x00007ffff7861fbd in FlushRenderCommands (renderer=0x555555642150) at /usr/src/debug/SDL3-3.1.6-1.fc41.x86_64/src/render/SDL_render.c:322
#24 SDL_FlushRenderer_REAL (renderer=0x555555642150) at /usr/src/debug/SDL3-3.1.6-1.fc41.x86_64/src/render/SDL_render.c:351
#25 0x00007ffff7beb0a4 in FlushRendererIfNotBatching (renderer=0x555555642150) at /usr/src/debug/sdl2-compat-2.30.50~git20241130.89e3c65-1.fc41.x86_64/src/sdl2_compat.c:4347
#26 FlushRendererIfNotBatching (renderer=renderer@entry=0x555555642150) at /usr/src/debug/sdl2-compat-2.30.50~git20241130.89e3c65-1.fc41.x86_64/src/sdl2_compat.c:4343
#27 0x00007ffff7bebdca in SDL_RenderCopy_REAL (renderer=0x555555642150, texture=<optimized out>, srcrect=<optimized out>, dstrect=<optimized out>) at /usr/src/debug/sdl2-compat-2.30.50~git20241130.89e3c65-1.fc41.x86_64/src/sdl2_compat.c:4796
#28 0x00007ffff7f71188 in PresentScreen () at /usr/src/debug/sdl12-compat-1.2.68-3.fc41.x86_64/src/SDL12_compat.c:6815
#29 0x00007ffff7f76fa6 in SDL_UpdateRects (surface12=<optimized out>, numrects=<optimized out>, rects12=<optimized out>) at /usr/src/debug/sdl12-compat-1.2.68-3.fc41.x86_64/src/SDL12_compat.c:7089
#30 0x00007ffff7f771d8 in SDL_UpdateRect (screen12=<optimized out>, x=<optimized out>, y=<optimized out>, w=<optimized out>, h=<optimized out>) at /usr/src/debug/sdl12-compat-1.2.68-3.fc41.x86_64/src/SDL12_compat.c:7108
#31 0x000055555555cb4c in updateall () at /usr/src/debug/icebreaker-2.2.2-5.fc41.x86_64/laundry.c:91
#32 0x0000555555560560 in setupintro () at /usr/src/debug/icebreaker-2.2.2-5.fc41.x86_64/intro.c:91
#33 intro () at /usr/src/debug/icebreaker-2.2.2-5.fc41.x86_64/intro.c:122
#34 0x00005555555571fa in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/icebreaker-2.2.2-5.fc41.x86_64/icebreaker.c:191
```

**Comment by slouken** [comment] 2024-12-03 22:25
Can you try with the latest main code? This codepath shouldn't be hit in this case.

**Comment by Conan-Kudo** [comment] 2024-12-03 23:32
Still an issue:

```
(gdb) bt
#0  0x000055555556c560 in flock ()
#1  0x00007fffcb621132 in mesa_db_flock (file=<optimized out>, op=<optimized out>) at ../src/util/mesa_cache_db.c:105
#2  mesa_db_lock (db=0x5555559b03c0) at ../src/util/mesa_cache_db.c:120
#3  0x00007fffcb621555 in mesa_db_load (db=db@entry=0x5555559b03c0, reload=reload@entry=false) at ../src/util/mesa_cache_db.c:346
#4  0x00007fffcb621ed3 in mesa_cache_db_open (db=db@entry=0x5555559b03c0, cache_path=<optimized out>) at ../src/util/mesa_cache_db.c:685
#5  0x00007fffcb60e3da in mesa_cache_db_multipart_init_part_locked (db=0x555555802140, part=0) at ../src/util/mesa_cache_db_multipart.c:60
#6  mesa_cache_db_multipart_init_part (db=db@entry=0x555555802140, part=part@entry=0) at ../src/util/mesa_cache_db_multipart.c:93
#7  0x00007fffcb60e667 in mesa_cache_db_multipart_init_part (db=0x555555802140, part=0) at ../src/util/mesa_cache_db_multipart.c:89
#8  mesa_cache_db_multipart_read_entry (db=db@entry=0x555555802140, cache_key_160bit=cache_key_160bit@entry=0x7fffffffb9e0 "\220\232\315O\300\217\354mv\304\303q\371\377\340\374\346\226j\263\377\177", size=size@entry=0x7fffffffb8f0) at ../src/util/mesa_cache_db_multipart.c:136
#9  0x00007fffcb600c7c in disk_cache_db_load_item (cache=cache@entry=0x555555801fb0, key=key@entry=0x7fffffffb9e0 "\220\232\315O\300\217\354mv\304\303q\371\377\340\374\346\226j\263\377\177", size=size@entry=0x7fffffffb9a8) at ../src/util/disk_cache_os.c:1167
#10 0x00007fffcb5ff2be in disk_cache_get (cache=cache@entry=0x555555801fb0, key=key@entry=0x7fffffffb9e0 "\220\232\315O\300\217\354mv\304\303q\371\377\340\374\346\226j\263\377\177", size=size@entry=0x7fffffffb9a8) at ../src/util/disk_cache.c:605
#11 0x00007fffcb578553 in vk_pipeline_cache_lookup_object (cache=0x5555557ab520, key_data=key_data@entry=0x5555559b9c20, key_size=key_size@entry=20, ops=ops@entry=0x7fffcbf6a510 <radv_pipeline_ops>, cache_hit=<optimized out>) at ../src/vulkan/runtime/vk_pipeline_cache.c:365
#12 0x00007fffcb4d3bc6 in radv_pipeline_cache_object_search (device=device@entry=0x55555587c080, cache=<optimized out>, cache@entry=0x0, pipeline=pipeline@entry=0x5555559b9be0, found_in_application_cache=found_in_application_cache@entry=0x7fffffffbb07) at ../src/amd/vulkan/radv_pipeline_cache.c:298
#13 0x00007fffcb4d4085 in radv_graphics_pipeline_cache_search (device=device@entry=0x55555587c080, cache=cache@entry=0x0, pipeline=pipeline@entry=0x5555559b9be0, found_in_application_cache=found_in_application_cache@entry=0x7fffffffbb07) at ../src/amd/vulkan/radv_pipeline_cache.c:314
#14 0x00007fffcb4da5f7 in radv_graphics_pipeline_compile (pipeline=pipeline@entry=0x5555559b9be0, pCreateInfo=pCreateInfo@entry=0x7fffffffc6b0, gfx_state=gfx_state@entry=0x7fffffffbd30, device=device@entry=0x55555587c080, cache=cache@entry=0x0, fast_linking_enabled=fast_linking_enabled@entry=false)
    at ../src/amd/vulkan/radv_pipeline_graphics.c:2730
#15 0x00007fffcb4dbbe8 in radv_graphics_pipeline_init (pipeline=pipeline@entry=0x5555559b9be0, device=device@entry=0x55555587c080, cache=cache@entry=0x0, pCreateInfo=pCreateInfo@entry=0x7fffffffc6b0, extra=extra@entry=0x0) at ../src/amd/vulkan/radv_pipeline_graphics.c:3134
#16 0x00007fffcb4dc95e in radv_graphics_pipeline_create (_device=_device@entry=0x55555587c080, _cache=_cache@entry=0x0, pCreateInfo=pCreateInfo@entry=0x7fffffffc6b0, extra=extra@entry=0x0, pAllocator=pAllocator@entry=0x0, pPipeline=pPipeline@entry=0x555555afc160) at ../src/amd/vulkan/radv_pipeline_graphics.c:3204
#17 0x00007fffcb4dccf9 in radv_CreateGraphicsPipelines (_device=<optimized out>, pipelineCache=<optimized out>, count=<optimized out>, pCreateInfos=<optimized out>, pAllocator=<optimized out>, pPipelines=<optimized out>) at ../src/amd/vulkan/radv_pipeline_graphics.c:3347
#18 0x00007ffff79a22fd in VULKAN_CreateGraphicsPipeline (driverData=<optimized out>, createinfo=<optimized out>) at /usr/src/debug/SDL3-3.1.6-1.fc41.x86_64/src/gpu/vulkan/SDL_gpu_vulkan.c:6454
#19 0x00007ffff78728e5 in MakePipeline (device=0x5555555ce740, shaders=0x5555557ed988, params=<synthetic pointer>) at /usr/src/debug/SDL3-3.1.6-1.fc41.x86_64/src/render/gpu/SDL_pipeline_gpu.c:180
#20 GPU_GetPipeline (cache=0x5555557ed9b8, shaders=0x5555557ed988, device=0x5555555ce740, params=<synthetic pointer>) at /usr/src/debug/SDL3-3.1.6-1.fc41.x86_64/src/render/gpu/SDL_pipeline_gpu.c:210
#21 Draw (data=data@entry=0x5555557ed980, cmd=0x5555559af980, num_verts=6, offset=0, prim=SDL_GPU_PRIMITIVETYPE_TRIANGLELIST) at /usr/src/debug/SDL3-3.1.6-1.fc41.x86_64/src/render/gpu/SDL_render_gpu.c:567
#22 0x00007ffff7872deb in GPU_RunCommandQueue (renderer=0x5555557e2850, cmd=<optimized out>, vertices=<optimized out>, vertsize=<optimized out>) at /usr/src/debug/SDL3-3.1.6-1.fc41.x86_64/src/render/gpu/SDL_render_gpu.c:814
#23 0x00007ffff7861fbd in FlushRenderCommands (renderer=0x5555557e2850) at /usr/src/debug/SDL3-3.1.6-1.fc41.x86_64/src/render/SDL_render.c:322
#24 SDL_FlushRenderer_REAL (renderer=0x5555557e2850) at /usr/src/debug/SDL3-3.1.6-1.fc41.x86_64/src/render/SDL_render.c:351
#25 0x00007ffff7bf00a4 in FlushRendererIfNotBatching (renderer=0x5555557e2850) at /usr/src/debug/sdl2-compat-2.30.50~git20241130.89e3c65-1.fc41.x86_64/src/sdl2_compat.c:4347
#26 FlushRendererIfNotBatching (renderer=renderer@entry=0x5555557e2850) at /usr/src/debug/sdl2-compat-2.30.50~git20241130.89e3c65-1.fc41.x86_64/src/sdl2_compat.c:4343
#27 0x00007ffff7bf0dca in SDL_RenderCopy_REAL (renderer=0x5555557e2850, texture=<optimized out>, srcrect=<optimized out>, dstrect=<optimized out>) at /usr/src/debug/sdl2-compat-2.30.50~git20241130.89e3c65-1.fc41.x86_64/src/sdl2_compat.c:4796
#28 0x00007ffff7f72f88 in PresentScreen () at /usr/src/debug/sdl12-compat-1.2.68^git20241009.6f0f603-1.fc41.x86_64/src/SDL12_compat.c:6818
#29 0x00007ffff7f78da6 in SDL_UpdateRects (surface12=<optimized out>, numrects=<optimized out>, rects12=<optimized out>) at /usr/src/debug/sdl12-compat-1.2.68^git20241009.6f0f603-1.fc41.x86_64/src/SDL12_compat.c:7092
#30 0x00007ffff7f78fd8 in SDL_UpdateRect (screen12=<optimized out>, x=<optimized out>, y=<optimized out>, w=<optimized out>, h=<optimized out>) at /usr/src/debug/sdl12-compat-1.2.68^git20241009.6f0f603-1.fc41.x86_64/src/SDL12_compat.c:7111
#31 0x000055555555cb4c in updateall () at /usr/src/debug/icebreaker-2.2.2-5.fc41.x86_64/laundry.c:91
#32 0x0000555555560560 in setupintro () at /usr/src/debug/icebreaker-2.2.2-5.fc41.x86_64/intro.c:91
#33 intro () at /usr/src/debug/icebreaker-2.2.2-5.fc41.x86_64/intro.c:122
#34 0x00005555555571fa in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/icebreaker-2.2.2-5.fc41.x86_64/icebreaker.c:191
```

**Comment by slouken** [comment] 2024-12-03 23:37
That's not running the latest SDL code from main:
`/usr/src/debug/SDL3-3.1.6-1.fc41.x86_64/src/render/SDL_render.c`

**Comment by Conan-Kudo** [comment] 2024-12-03 23:37
This is reproducible on Fedora 41 with the following steps:

```bash
$ sudo dnf copr enable ngompa/SDL2onSDL3
$ sudo dnf swap SDL2 sdl2-compat
$ sudo dnf up sdl12-compat
$ sudo dnf install icebreaker
$ icebreaker
```

**Comment by Conan-Kudo** [comment] 2024-12-03 23:37
> That's not running the latest SDL code from main: `/usr/src/debug/SDL3-3.1.6-1.fc41.x86_64/src/render/SDL_render.c`

Ah, that's what you meant. Let me give it a try.

**Comment by Conan-Kudo** [comment] 2024-12-03 23:53
It's still crashing with the latest SDL3 from mainline, but I'm back to the same backtrace as the original post:

```
(gdb) bt
#0  0x000055555556c560 in flock ()
#1  0x00007fffe6abc992 in mesa_db_flock (file=<optimized out>, op=<optimized out>) at ../src/util/mesa_cache_db.c:105
#2  mesa_db_lock (db=0x7fffcc000d00) at ../src/util/mesa_cache_db.c:120
#3  0x00007fffe6abcdb5 in mesa_db_load (db=db@entry=0x7fffcc000d00, reload=reload@entry=false) at ../src/util/mesa_cache_db.c:346
#4  0x00007fffe6abd713 in mesa_cache_db_open (db=db@entry=0x7fffcc000d00, cache_path=<optimized out>) at ../src/util/mesa_cache_db.c:685
#5  0x00007fffe6a9db8a in mesa_cache_db_multipart_init_part_locked (db=0x555555782550, part=0) at ../src/util/mesa_cache_db_multipart.c:60
#6  mesa_cache_db_multipart_init_part (db=db@entry=0x555555782550, part=part@entry=0) at ../src/util/mesa_cache_db_multipart.c:93
#7  0x00007fffe6a9de07 in mesa_cache_db_multipart_init_part (db=0x555555782550, part=0) at ../src/util/mesa_cache_db_multipart.c:89
#8  mesa_cache_db_multipart_read_entry (db=db@entry=0x555555782550, cache_key_160bit=cache_key_160bit@entry=0x7fffdd859cc0 "\237\315OS\016a\263\0165\367\va=\233IrM\271\343Y\377\177", size=size@entry=0x7fffdd859c20) at ../src/util/mesa_cache_db_multipart.c:136
#9  0x00007fffe6a8f72c in disk_cache_db_load_item (cache=cache@entry=0x5555557823c0, key=key@entry=0x7fffdd859cc0 "\237\315OS\016a\263\0165\367\va=\233IrM\271\343Y\377\177", size=size@entry=0x7fffdd859cb8) at ../src/util/disk_cache_os.c:1167
#10 0x00007fffe6a8db5e in disk_cache_get (cache=0x5555557823c0, key=0x7fffdd859cc0 "\237\315OS\016a\263\0165\367\va=\233IrM\271\343Y\377\177", size=0x7fffdd859cb8) at ../src/util/disk_cache.c:605
#11 0x00007fffe730bc1b in si_shader_cache_load_shader (sscreen=sscreen@entry=0x5555556ee2e0, ir_sha1_cache_key=ir_sha1_cache_key@entry=0x7fffdd859d40 "\270\276l", shader=shader@entry=0x555555a0ede8) at ../src/gallium/drivers/radeonsi/si_state_shaders.cpp:415
#12 0x00007fffe7360859 in si_create_compute_state_async (job=job@entry=0x555555a0e860, gdata=gdata@entry=0x0, thread_index=thread_index@entry=0) at ../src/gallium/drivers/radeonsi/si_compute.c:162
#13 0x00007fffe6a9ac41 in util_queue_thread_func (input=input@entry=0x5555557bc590) at ../src/util/u_queue.c:309
#14 0x00007fffe6abe70c in impl_thrd_routine (p=<optimized out>) at ../src/c11/impl/threads_posix.c:67
#15 0x00007ffff7d95cd7 in start_thread (arg=<optimized out>) at pthread_create.c:448
#16 0x00007ffff7e19c8c in __GI___clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
```

**Comment by Conan-Kudo** [comment] 2024-12-03 23:55
And this is the SDL stack I've got:

```
ngompa@fedora ~> rpm -q SDL3
SDL3-3.1.6^git20241203.1804.31d0990-1.fc41.x86_64
SDL3-3.1.6^git20241203.1804.31d0990-1.fc41.i686
ngompa@fedora ~> rpm -q sdl2-compat
sdl2-compat-2.30.50~git20241130.89e3c65-1.fc41.x86_64
sdl2-compat-2.30.50~git20241130.89e3c65-1.fc41.i686
ngompa@fedora ~> rpm -q sdl12-compat
sdl12-compat-1.2.68^git20241009.6f0f603-1.fc41.x86_64
```

**Comment by slouken** [comment] 2024-12-03 23:56
Hmm, it looks like a crash in Mesa regardless of where it's called from. Can you run with valgrind to see if we're hitting invalid memory accesses before that point?

**Comment by Conan-Kudo** [comment] 2024-12-04 00:03
Here's what I've got: [valgrind-icebreaker-log.txt](https://github.com/user-attachments/files/18000746/valgrind-icebreaker-log.txt)

**Comment by slouken** [comment] 2024-12-04 00:11
That's interesting, is there a function called flock() in icebreaker? Is Mesa somehow calling into application code instead of a library function?
```
==661444== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==661444==  Bad permissions for mapped region at address 0x120560
==661444==    at 0x120560: ??? (in /usr/bin/icebreaker)
==661444==    by 0x13615DB4: mesa_db_load (mesa_cache_db.c:346)
```

**Comment by Conan-Kudo** [comment] 2024-12-04 00:13
There's a struct called `flock` in the code: https://github.com/mattdm/icebreaker/blob/7180612a54b42a5f52e15238d7ddf64f0b879e51/level.h#L47

**Comment by slouken** [comment] 2024-12-04 00:21
What happens if you rename that?

**Comment by Conan-Kudo** [comment] 2024-12-04 00:46
It fixes it! Submitted patch: https://github.com/mattdm/icebreaker/pull/17

**Comment by slouken** [comment] 2024-12-04 00:48
Great!

It seems odd that a data symbol would conflict with a function entry point in a shared library, but that's not an SDL bug, so I'll close this out. :)

**Closed by slouken** 2024-12-04 00:48 UTC

**Comment by icculus** [comment] 2024-12-04 04:38
Does Fedora build the binary with a flag that causes all symbols to export even though it isn't a shared library? I don't know what off the top of my head, but I'm wondering if there's something Ubuntu did/didn't do that caused this to work for me and not for you.

**Comment by smcv** [comment] 2024-12-04 11:39
> It seems odd that a data symbol would conflict with a function entry point in a shared library

To the best of my knowledge, ELF doesn't differentiate: symbols are symbols (in practice data and function pointers have different relocations, but the runtime linker neither knows nor cares which kind of symbol you are trying to access). You can attempt to call a data pointer and it will go exactly as badly as you'd expect.

> Does Fedora build the binary with a flag that causes all symbols to export even though it isn't a shared library?

Does Fedora perhaps use link-time optimization (LTO) by default? Some newer (and less risk-averse) distributions are starting to do that, and it can easily cause crashes in situations that were previously undefined behaviour but "accidentally worked" anyway.

**Comment by Conan-Kudo** [comment] 2024-12-04 11:53
We do use LTO by default.
