### ISSUE TITLE
Are there any plans to make a release?

### ISSUE THREAD

**Issue by Croydon** [libsdl-org/sdl12-compat#142] opened 2021-11-16 20:30 UTC
I'm thinking about packaging sdl12-compat for [Conan](https://conan.io).

Are there any plans for tagging sdl12-compat with official version numbers?

I have seen that Fedora 35 uses `0.0.1~git.20211107.a10d6b6-1` as the version number, due to the lack of an official one.

Providing official releases can increase confidence in contrast to using a "random git commit".

**Comment by slouken** [comment] 2021-11-16 23:22
Yes, this is a good idea.

**Comment by sezero** [comment] 2021-11-17 17:04
Duplicate of https://github.com/libsdl-org/sdl12-compat/issues/53 - Closing.

**Closed by sezero** 2021-11-17 17:04 UTC
