### ISSUE TITLE
netsurf-framebuffer: Differing behavior between sdl & sdl12-compat

### ISSUE THREAD

**Issue by mil** [libsdl-org/sdl12-compat#155] opened 2022-01-16 19:38 UTC
I'm trying to use netsurf's framebuffer interface with sdl12-compat.

The usecase for this is from framebuffer you can run:
```
netsurf-fb -f sdl
``` 

When built with normal SDL1, netsurf launches fine.
With sdl12-compat, it segfaults as the normal user (which works fine with SDL1), and complains about permissions; if run as root the entire screen just turns black and VT switching stops working as well.

Is there some extra env var or something I need to add when running with sdl12-compat to make it function normally like it does with SDL?

Info on netsurf's framebuffer interface:
https://ci.netsurf-browser.org/jenkins/job/docs-netsurf/doxygen/md_docs_using-framebuffer.html

**Comment by icculus** [comment] 2022-01-24 15:05
So this works for me on X11, so I'm guessing this is an SDL2 deficiency with a framebuffer device.

SDL 1.2 will work with /dev/fb* ... I'm guess this isn't working with sdl12-compat because the system in question doesn't work with kmsdrm (or SDL2 has a bug in that backend), or it chose the directfb driver which hasn't been touched in _years_.

In any case, I don't think this an sdl12-compat bug. It could be a system issue or SDL2 needs a real /dev/fb backend that works with the software renderer, or something.

If this is a custom embedded system, you might be better off sticking with the real SDL 1.2. I'm going to close this, but if you want to keep tracking this down, we can figure out where a bug should be filed, though!

**Comment by Newbytee** [comment] 2022-01-24 16:55
> So this works for me on X11, so I'm guessing this is an SDL2 deficiency with a framebuffer device.

Yeah, it worked for me with X11 and Wayland on Alpine too.

> If this is a custom embedded system, you might be better off sticking with the real SDL 1.2. I'm going to close this, but if you want to keep tracking this down, we can figure out where a bug should be filed, though!

It's a Linux distribution (postmarketOS, which largely uses Alpine Linux' repos). I want to replace SDL 1.2 with sdl12-compat for reasons, but Miles noticed that this caused issues in his framebufferphone UI and therefore this issue was made. As I see it, sticking with SDL 1.2 would not be ideal as I'd like to drop it from the distribution entirely so I can ensure that sdl12-compat always is used (proprietary games won't be running on Alpine anyway — musl). So yes, I would appreciate if we could track this down. Where do we start?

**Comment by icculus** [comment] 2022-01-24 20:53
> Where do we start?

The first and most important question is what video backend did SDL2 end up choosing? 

The fastest way to do this is load netsurf-fb under gdb, set a breakpoint on `SDL_Init_REAL`, run with "-f sdl". When it hits the breakpoint, type "fin" to run until SDL_Init finishes, and then force it to run `SDL_GetCurrentVideoDriver`.

On my system, it looked like this:

```
icculus@lucha:~/projects/sdl12-compat/cmake-build$ LD_LIBRARY_PATH=/home/icculus/projects/sdl12-compat/cmake-build SDL12COMPAT_DEBUG_LOGGING=1 gdb /usr/bin/netsurf-fb 
GNU gdb (Ubuntu 11.1-0ubuntu2) 11.1
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/netsurf-fb...
(No debugging symbols found in /usr/bin/netsurf-fb)
(gdb) b SDL_Init_REAL
Function "SDL_Init_REAL" not defined.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 1 (SDL_Init_REAL) pending.
(gdb) r -f sdl
Starting program: /usr/bin/netsurf-fb -f sdl
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
INFO: sdl12-compat, built on Jan 24 2022 at 13:46:02, talking to SDL2 2.0.20
INFO: FIXME: there is never a parachute in SDL2, should we catch segfaults ourselves? (SDL_Init:1866)
INFO: FIXME: support SDL_INIT_EVENTTHREAD where it makes sense? (SDL_InitSubSystem:1832)

Breakpoint 1, SDL_Init_REAL (flags=33) at /home/icculus/projects/SDL/src/SDL.c:330
warning: Source file is more recent than executable.
330	    return SDL_InitSubSystem(flags);
(gdb) fin
Run till exit from #0  SDL_Init_REAL (flags=33) at /home/icculus/projects/SDL/src/SDL.c:330
[New Thread 0x7ffff56e4640 (LWP 2181815)]
[New Thread 0x7fffeb401640 (LWP 2181819)]
[New Thread 0x7fffeabc0640 (LWP 2181820)]
[Thread 0x7fffeabc0640 (LWP 2181820) exited]
[New Thread 0x7fffeabc0640 (LWP 2181821)]
[Thread 0x7fffeabc0640 (LWP 2181821) exited]
0x00007ffff683674f in SDL_Init (a=33) at /home/icculus/projects/SDL/src/dynapi/SDL_dynapi_procs.h:85
warning: Source file is more recent than executable.
85	SDL_DYNAPI_PROC(int,SDL_Init,(Uint32 a),(a),return)
Value returned is $1 = 0
(gdb) p (const char *) SDL_GetCurrentVideoDriver()
$2 = 0x7ffff6ac0e19 "x11"
```

The final line is the magic (here, I ran it under X11). The LD_LIBRARY_PATH line let me switch between SDL-1.2 and sdl12-compat.

We need to see what this reports for real SDL 1.2 and sdl12-compat. But my guess is 1.2 is going to say "fbcon" and sdl12-compat is going to say "kmsdrm" and at that point this will be, at best, an SDL2 issue.

The SDL code from netsurf is here, fwiw: https://source.netsurf-browser.org/libnsfb.git/tree/src/surface/sdl.c

**Comment by icculus** [comment] 2022-02-08 18:20
Is there any word on this? I don't want to nag, but if possible I'd like to have this fixed in 1.2.50 (or have the issue moved to SDL2 for further consideration, if appropriate).

**Comment by mil** [comment] 2022-02-08 18:27
I'll do some testing within next few days or by next week to determine the video backends for SDL2 vs sdl12-compat to confirm your theory that 1.2 is using fbcon and compat is using kmsdrm.

Thanks for the info / instructions on debugging

**Comment by Newbytee** [comment] 2022-04-30 11:55
So I tried going through the debugging steps, but it segmentation faults when I do `fin`. It seems that the crash happens in DirectFB because it is unable to open the framebuffer device. So while I'm not able to get the return value of the mentioned function, I assume this would indicate that sdl12-compat/SDL 2 is using DirectFB rather than KMSDRM?

**Comment by nekopsykose** [comment] 2022-07-05 22:37
> I assume this would indicate that sdl12-compat/SDL 2 is using DirectFB rather than KMSDRM?

did you try `SDL_VIDEODRIVER=kmsdrm`?

**Comment by nekopsykose** [comment] 2022-07-05 23:08
tried the above on 12-compat, and indeed by default it picks directfb and segfaults, and if you force kmsdrm it doesn't work (sdl says it's not available, so something else is missing for that one).  

for real sdl 1.2, it uses fbcon.  

everything else is the same as in the initial report- the segfault isn't really a segfault as it's just denied permissions, and fixing that freezes the display. indeed seems like either a directfb or an sdl2 issue specifically, with nothing caused by 12-compat itself

**Closed** 2022-09-01 19:12 UTC
Labels: waiting

**Comment by icculus** [comment] 2022-09-01 19:15
I believe I just fixed this issue, but I do not have an environment to test this.

If the latest sdl12-compat (and possibly SDL 2.24.0) doesn't fix your issue, please let me know and I'll reopen this bug. Thanks!

**Comment by nekopsykose** [comment] 2022-09-01 20:35
can confirm- with latest master, it actually works better than sdl1, as it's centered on the screen..  

thanks!

**Comment by icculus** [comment] 2022-09-02 01:49
I love it.  :)
