### ISSUE TITLE
Windowing issues and high CPU usage in Dwarf Fortress

### ISSUE THREAD

**Issue by autumnontape** [libsdl-org/sdl12-compat#127] opened 2021-08-12 11:05 UTC
When starting Dwarf Fortress on X.Org or Xwayland with sdl12-compat, the game immediately hangs on a black screen, using ~95% of one CPU (with X.Org or Xwayland using the rest) and logging this to stdout:

<details>

```
Sound devices available:
OpenAL Soft
Picking OpenAL Soft. If your desired device was missing, make sure you have the appropriate 32-bit libraries installed. If you wanted a different device, configure ~/.openalrc appropriately.
Perfect OpenAL context attributes GET
Loading bindings from data/init/interface.txt
New window size: 640x300
Font size: 8x12
Resizing grid to 80x25
Resizing font to 8x12

Resetting textures
New window size: 640x300
Font size: 8x12
Resizing grid to 80x25
Resizing font to 8x12

New window size: 640x300
Font size: 8x12
Resizing grid to 80x25
Resizing font to 8x12

New window size: 640x300
Font size: 8x12
Resizing grid to 80x25
Resizing font to 8x12

New window size: 640x300
Font size: 8x12
Resizing grid to 80x25
Resizing font to 8x12

New window size: 640x300
Font size: 8x12
Resizing grid to 80x25
Resizing font to 8x12

New window size: 640x300
Font size: 8x12
Resizing grid to 80x25
Resizing font to 8x12

New window size: 640x300
Font size: 8x12
Resizing grid to 80x25
Resizing font to 8x12
```

\[repetition continues...]
</details>

It doesn't respond to the X button or normal kill signals and must be killed with `kill -9` when in this state. Alternatively, maximizing the window fixes it, ending the hang and causing the game to behave normally (and stopping the repeated logs), but still with significantly higher CPU usage than it exhibits when maximized with SDL classic (~40% vs ~7% on the title screen on my machine). Modifying the window size further seems to have unpredictable results, with the game alternately hanging and behaving normally. It hung while maximized during my experimentation, which suggests window size isn't the only factor.

Running the game with `SDL_VIDEODRIVER=wayland` had similar results, showing a black window and using 100% of one CPU while producing an identical log to stdout. However, the window had no decorations, and each time I maximized it with a keyboard shortcut, it immediately restored itself to its previous size and continued to hang. I had to `kill -9` it.

I'm running Dwarf Fortress from the official Arch Linux x86_64 [`dwarffortress 0.47.05-1`](https://archlinux.org/packages/community/x86_64/dwarffortress/) package, with sdl12-compat from the AUR x86_64 [`sdl2_compat12-git r453.4337eda-1`](https://aur.archlinux.org/packages/sdl2_compat12-git) package (built from commit 4337eda, as suggested by the version string), and SDL 2 from the official [`sdl2 2.0.16-1`](https://archlinux.org/packages/extra/x86_64/sdl2/) package. I'm using the GNOME 40 desktop environment. I also tested the game with SDL classic from the official [`sdl 1.2.15-14`](https://archlinux.org/packages/community/x86_64/sdl/) package, and it ran normally with no hangs, repeated logs, or high CPU usage.

**Comment by sulix** [comment] 2021-08-13 07:27
This seems to be a results of ``SDL_WINDOWEVENT_SIZE_CHANGED`` messages being passed through. Just ignoring them is enough to get this to work. I've done this in PR #128.

In particular, the problem is that in SDL 1.2, the recommended course of action upon getting an ``SDL_VIDEORESIZE`` event is to call ``SDL_SetVideoMode()`` with the new size. But SDL 2.0 generates a ``SDL_WINDOWEVENT_SIZE_CHANGED`` which sets the original size. So if an application doesn't check that the size is actually different to what they're expecting, then they end up in an infinite loop.

It possibly requires a bit more thought to work out exactly how to handle 1.2's ``SDL_VIDEORESIZE``/``SDL_ResizeEvent`` events. Very few SDL 1.2 applications actually have resizable windows, so this isn't well tested. At the moment, we're destroying and recreating the window on every ``SDL_SetVideoMode()`` call, which means that this happens on every ``SDL_VIDEORESIZE`` event, making resizing viscerally unpleasant. So there's still work to do, but this at least lets Dwarf Fortress start.

**Comment by autumnontape** [comment] 2021-08-13 19:16
That PR fixes the hanging and 100% CPU usage on my machine as well! I can even run the game as a Wayland application, though the window decorations are still missing.

The unusually high (not 100%) CPU usage remains, though. With SDL classic, DF uses 7% CPU at the title screen, regardless of window size. With sdl12-compat, it uses 14% CPU at the title screen at the default window size (640 by 300 pixels), and 38% when maximized (1920 by 1011 pixels). It's very steady in every case.

**Comment by sulix** [comment] 2021-08-13 21:30
For the Wayland window decorations — these require the [``libdecor``](https://gitlab.gnome.org/jadahl/libdecor) library. Since these are only supported in the very latest SDL 2.0.16, and ``libdecor`` has only just had its first release it looks like Arch might not support it yet: the SDL package you linked doesn't list it as a dependency.

There is an AUR package for it, though: https://aur.archlinux.org/packages/libdecor/ — nothing seems to depend on it yet.

Window decorations will appear in Wayland compositors which support server-side decorations — like KDE/KWin — even without ``libdecor``, but GNOME requires SDL to draw its own, and that is done with ``libdecor``.

**Comment by sezero** [comment] 2021-08-14 07:25
Fixed by PR #128

**Closed by sezero** 2021-08-14 07:25 UTC

**Comment by sulix** [comment] 2021-08-14 09:21
FWIW: I looked into the CPU usage briefly, and there's not much difference on my machine — yes, ``sdl12compat``'s usage is probably a bit higher, and probably does scale a bit with the window resolution, but it stays well under 5% here.

This definitely does seem (given that it scales with resolution) that it's a result of ``sdl12-compat``'s 2D rendering path being a bit slower than SDL 1.2's. This is to be expected at this point, as it hasn't seen any real optimisation yet.

I tried hacking some quick optimisations together, but they didn't have a noticeably impact on my machine. Still, you can check out these commits if the CPU use is really being a problem: between them, things should in theory be slightly faster:
https://github.com/sulix/sdl12-compat/commit/08c689eff565873f066530bef60a7f0423d417f4
https://github.com/sulix/sdl12-compat/commit/ce2a3497d3d89a6f48e2e68891b4ea7922e71156

**Comment by sulix** [comment] 2021-08-14 10:07
FYI, I've also opened PR #129 to handle the resizing being janky (at least under KDE/KWin).

**Comment by autumnontape** [comment] 2021-08-14 19:40
> I tried hacking some quick optimisations together, but they didn't have a noticeably impact on my machine. Still, you can check out these commits if the CPU use is really being a problem: between them, things should in theory be slightly faster:
> [sulix@08c689e](https://github.com/sulix/sdl12-compat/commit/08c689eff565873f066530bef60a7f0423d417f4)
> [sulix@ce2a349](https://github.com/sulix/sdl12-compat/commit/ce2a3497d3d89a6f48e2e68891b4ea7922e71156)

Those patches don't seem to make a difference on my machine, either, but I appreciate you looking into it!
