### ISSUE TITLE
Lack of unicode support breaks keyboard input in some applications.

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/sdl12-compat#17] opened 2021-02-11 05:35 UTC
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** unspecified
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2019-11-24 01:51:19 +0000, Lyle wrote:

> Some applications, such as the game Frozen Synapse and this legacy SDL tutorial from Lazy Foo http://www.lazyfoo.net/SDL_tutorials/lesson23/index.php pull keyboard input through event.key.keysym.unicode. Currently, this is always set to 0, which results in these applications failing to recognize any input. This occurs due to the following line in SDL12_compat.c:
> 
>     event12.key.keysym.unicode = 0;  FIXME("unicode");
> 
> However, since the unicode character set is a superset of ASCII, we can provide partial functionality here very easily just by passing through the sym value. For example:
> 
>     event12.key.keysym.unicode = event12.key.keysym.sym;
> 
> I'll admit that I don't know exactly what will happen here if someone does input a character which requires unicode support. However, I have verified that this change restores keyboard input functionality for me for the sign-in screen of the game Frozen Synapse as well as the above linked legacy Lazy Foo tutorial. Until such time that someone is prepared to fully implement the needed bits for unicode, I think this or something very much like it would be a change for the better.

**Comment by sezero** [comment] 2021-02-21 01:06
Reproduced the issue in quakespasm (http://quakespasm.sf.net/): 
typing in the game console doesn't work at all, because its SDL-1.2
code rely on event.key.keysym.unicode.

With the proposed change above, basic typing becomes possible
(but uppercase typing does not..)

**Comment by sezero** [comment] 2021-02-21 15:50
Implemented the proposed workaround as commit 65264db31389 for now.

**Comment by sezero** [comment] 2021-05-18 19:49
Should be fixed after commits 65264db31389c, b635c63ea4c01, ebfcc6e76383d,
and 35fa90b5d1a73. Closing.

**Closed by sezero** 2021-05-18 19:49 UTC
Labels: bug
